---
services:
  unifi-db:
    # UGREEN or Synology models later than x20:
    image: docker.io/mongo:7
    # Synology models with Celeron and Atom CPUs:
    # image: docker.io/mongo:4.4
    container_name: unifi-db
    volumes:
      - /volume1/docker/unifi-nwa/data:/data/db
      - /volume1/docker/unifi-nwa/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=CHANGEME
      - MONGO_USER=unifi
      - MONGO_PASS=CHANGEME
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:9.5.21
    container_name: unifi-network-application
    depends_on:
      unifi-db:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=CHANGEME
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    #  - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - /volume1/docker/unifi-nwa/config:/config
    ports:
      - 8444:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    #  - 1900:1900/udp #optional
    #  - 8843:8843 #optional
    #  - 8880:8880 #optional
    #  - 6789:6789 #optional
    #  - 5514:5514/udp #optional
    restart: unless-stopped

networks:
  default:
    name: unifi-net
    external: true
